fairseq-train ../../data_bin/v2_distilled_indic_en_HQ_bin/final_bin \
--max-source-positions 210 \
--max-target-positions 210 \
--max-epoch 1 \
--arch transformer_1x_v0 \
--task translation_capture_fisher_information \
--criterion label_smoothed_cross_entropy \
--source-lang SRC \
--target-lang TGT \
--label-smoothing 0.1 \
--optimizer adam \
--adam-betas "(0.9, 0.98)" \
--clip-norm 1.0 \
--warmup-init-lr 1e-07 \
--warmup-updates 4000 \
--lr-scheduler inverse_sqrt \
--dropout 0.2 \
--no-save \
--patience 5 \
--skip-invalid-size-inputs-valid-test \
--disable-validation \
--update-freq 3 \
--distributed-world-size 1 \
--max-tokens 8192 \
--lr 3e-5 \
--restore-file ../checkpoints/base/checkpoint_best.pt \
--save-precision-matrices-to ../checkpoints/precision_matrices_hq.pt \
--reset-lr-scheduler \
--reset-meters \
--reset-dataloader \
--reset-optimizer \
--num-workers 32
