fairseq-train ../../data_dir/v2_distilled_indic_en_sample_bin/final_bin \
--max-source-positions 210 \
--max-target-positions 210 \
--max-epoch 1 \
--arch transformer \
--activation-fn gelu \
--encoder-normalize-before \
--decoder-normalize-before \
--layernorm-embedding \
--task translation_with_fisher_information \
--criterion label_smoothed_cross_entropy \
--source-lang SRC \
--target-lang TGT \
--label-smoothing 0.1 \
--optimizer adam \
--adam-betas "(0.9, 0.98)" \
--clip-norm 1.0 \
--warmup-init-lr 1e-07 \
--warmup-updates 4000 \
--lr-scheduler inverse_sqrt \
--dropout 0.2 \
--no-save \
--patience 5 \
--skip-invalid-size-inputs-valid-test \
--disable-validation \
--update-freq 16 \
--distributed-world-size 1 \
--max-tokens 2048 \
--lr 5e-4 \
--restore-file ../checkpoints/base/checkpoint_best.pt \
--reset-lr-scheduler \
--reset-meters \
--reset-dataloader \
--reset-optimizer \
--num-workers 16