#/bin/bash

fairseq-train $1/v2_0_binarized:$1/v2_10_binarized:$1/v2_20_binarized:$1/v2_30_binarized:$1/v2_40_binarized:$1/v2_50_binarized:$1/v2_60_binarized:$1/v2_70_binarized:$1/v2_80_binarized:$1/v2_90_binarized:$1/v2_100_binarized \
--max-source-positions 210 \
--max-target-positions 210 \
--max-update 1000000 \
--max-tokens 1536 \
--arch transformer_4x_v0 \
--encoder-recurrent-stacking 6 \
--decoder-recurrent-stacking 6 \
--dropout 0.2 \
--criterion label_smoothed_cross_entropy \
--label-smoothing 0.1 \
--source-lang SRC \
--target-lang TGT \
--lr-scheduler inverse_sqrt \
--optimizer adam \
--adam-betas "(0.9, 0.98)" \
--clip-norm 1.0 \
--warmup-init-lr 1e-07 \
--lr 0.0005 \
--warmup-updates 4000 \
--save-dir ../checkpoints/4x-recurrent-stacking \
--save-interval 1 \
--keep-last-epochs 1 \
--patience 5 \
--skip-invalid-size-inputs-valid-test \
--run-sanity-val-steps \
--update-freq 1 \
--distributed-world-size 1 \
--memory-efficient-fp16 \
--num-workers 16 \
--user-dir ../model_configs \
--eval-bleu \
--eval-bleu-args '{"beam": 5, "lenpen": 1.0}' \
--eval-bleu-detok moses \
--eval-bleu-remove-bpe \
--wandb-project Indic-En-Distillation
